### ISSUE TITLE
markdown table

### ISSUE THREAD

**Issue by jacealan** [thekimk/All-About-Financial-Data-Science#1]
패캠 금융공학 강의 잘듣고있습니다. 시계열 강의에 이어 교수님강의 또 듣게 되었네요.
올려주신 ipynb를 jupyter lab에서 보면 table이 깨져서 확인해보니, 테이블 경계표시에서 정렬을 빼고 |---|---| 로 바꾸면 되네요. 저처럼 lab 사용하는 이가 있을 수 있어서 올려둡니다.

**Comment by thekimk** [comment]
이슈를 알려주셔서 감사합니다.
모든 테이블이 출력되지 않는 것은 아니더군요.
자세히 확인해보니 깃허브 업로드 과정에서 테이블 정렬에 "공백"이 추가가 되어서 표시되지 않는 것으로 확인하였습니다.
정렬을 뺄 필요는 없고 정렬 앞뒤로 공백이 잇으면 공백만 제거해 주시면 됩니다 (ex. |:---:   | -> |:---:|)
일단, 주말동안 급하게 모든 파일에 대해 공백을 제거하여 다시 업로드를 하였습니다!
Notebook이든 Lab이든 테이블이 제대로 표기될 것입니다.
추가적인 이슈있으면 언제든지 알려주세요! 감사합니다.

**Comment by thekimk** [comment]
이슈를 종료하겠습니다.
혹시 추가적인 오류가 있다면 알려주세요 감사합니다!
