### ISSUE TITLE
Numpy 문제와 관련입니다.

### ISSUE THREAD

**Issue by verdantpond** [thekimk/All-About-Financial-Data-Science#2]
세밀한 강의에 많은 도움을 받고 있습니다.
Numpy강의 마지막에 있는 문제를 풀어 볼려고 하는데 파일을 어떻게 찾아야 하는지요? 이곳에도 파일이 없고...구글 검색을 해보니....여러 가지가 나오고 어떤걸 사용해야 할지 당황했습니다.
파일을 올려주시면 학습에 많은 도움이 될 거 같습니다.
감사합니다.

**Comment by thekimk** [comment]
실습파일이 누락되었군요!
알려주셔서 감사합니다. 지금 바로 실습 파일을 업데이트 하였으니, 강의자료를 다시 다운 받으셔서 강의내용의 경로로 파일을 불러오시면 문제없이 로딩이 되실겁니다.
또 추가적인 이슈가 있다면 언제든지 알려주십시요 감사합니다.

**Comment by thekimk** [comment]
이슈를 종료하겠습니다.
혹시 추가적인 오류가 있다면 알려주세요 감사합니다!
