### ISSUE TITLE
Part5-2. (파이썬기초) 파이썬 도구 익히기_Chapter5  'The notebook took too long to render.' 메시지 노출 이슈

### ISSUE THREAD

**Issue by psefosh** [thekimk/All-About-Financial-Data-Science#3]
https://github.com/thekimk/All-About-Financial-Data-Science/blob/main/Practice1-4_Basic_ConditionLoop_KK.ipynb

해당 강의 자료 클릭 시
The notebook took too long to render.

노출되며 강의자료가 보이지 않습니다.

확인하여 강의자료를 확인할 수 있는 방법을 알려주시면 감사하겠습니다.

감사합니다.

**Comment by thekimk** [comment]
안녕하세요 혹시 메일로도 문의주시지 않으셨나요?
만약 그렇다면 제가 16일 오후 9시 22분에 답변을 드렸는데 확인해 보시기 바랍니다.

만약 그렇지 않다면 아래 답변을 참고하시기 바랍니다.
Github는 기본적으로 파일 공유장소이며 뷰어는 아닙니다.
그래서 용량이 작은 강의파일은 종류를 막론하고 열리지만 용량이 크면 열리지 않습니다.
제대로 보시려면 Anaconda 설치시 설치되는 Jupyter Noterbook으로 보셔야 합니다.
아직 설치를 안하신건가요??
